baseURL = "http://jeremyzz830.github.io"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en"
paginate = 20
publishDir = "docs"
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
pygmentscodefences = true
theme = "hugo-coder"
title = "Jiaming Zhang"
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
fontbody = "Raleway"
fontheading = "Raleway"
# Changing font here is not enough, also change in _variables.css

author = "Jiaming Zhang"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
avatarURL = "images/IMG_0821.JPG"
description = "Jiaming's personal website"
info = [" <i>Veritas vos Liberabit</i> / <i>The truth will set you free</i> / <i>真理必将使你自由</i> "]
keywords = "blog,developer,personal"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "light"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# custom the favicon for the website
favicon = "images/polyu-logo.png"

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
prefetchsrc = ["'self'"]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/",
]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/",
]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
icon = "fa fa-2x fa-orcid"
name = "ORCID"
url = "https://orcid.org/0009-0002-6787-8590"
weight = 5

[[params.social]]
icon = "fa fa-2x fa-graduation-cap"
name = "Google Scholar"
weight = 6

[[params.social]]
icon = "fa fa-2x fa-github"
name = "Github"
url = "https://github.com/jeremyzz830/"
weight = 1

[[params.social]]
icon = "fa fa-2x fa-gitlab"
name = "Gitlab"
url = "https://git.lcsr.jhu.edu/jzhan282"
weight = 2

[[params.social]]
icon = "fa fa-2x fa-c"
name = "CSDN"
url = "https://blog.csdn.net/weixin_45367061?spm=1010.2135.3001.5421"
weight = 4

[[params.social]]
icon = "fa fa-2x fa-linkedin-square"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jeremy-zhang-540042237/"
weight = 3

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

# [[params.social]]
# name = "RSS"
# icon = "fa fa-2x fa-rss"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = "EN"

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "CV"
url = "cv/"
weight = 3

[[languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 5

[[languages.en.menu.main]]
name = "Publications"
url = "publications/"
weight = 4

[languages.pt-cn]
languageName = "Chinese"
title = "张嘉铭"

[[languages.pt-cn.menu.main]]
name = "出版物"
url = "publications/"

[[languages.pt-cn.menu.main]]
name = "简历"
url = "cv/"
weight = 3

# [languages.pt-br.params]
# author = "João Ninguém"
# info = "Full Stack DevOps e Mágico"
# description = "Sítio pessoal de João Ninguém"
# keywords = "blog,desenvolvedor,pessoal"

# [[languages.pt-br.menu.main]]
# name = "Sobre"
# weight = 1
# url = "about/"

# [[languages.pt-br.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.pt-br.menu.main]]
# name = "Projetos"
# weight = 3
# url = "projects/"

# [[languages.pt-br.menu.main]]
# name = "Contato"
# weight = 5
# url = "contact/"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = true
[markup.goldmark.parser.attribute]
block = false
title = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = true
